### ISSUE TITLE
Task 2

### ISSUE THREAD

**Issue by trigolos** [akondratsky/ReactJsMentoring2019Q1RU#1]
1.  MiniCssExtractPlugin need only in production mode.
```javascript
plugins: [
    // ...
    !isProduction&& new MiniCssExtractPlugin({
      filename: '[name].css',
      chunkFilename: '[id].css',
    }),
  ].filter(Boolean),
```
2.  Many constructions like `isProduction ? false : true` that can be simplified to `!isProduction`
3.  With devtool = 'eval' will be harder to debug code because you will see generated code. It is better to use mod that provides original source, like `cheap-module-eval-source-map`
See more about available devtool modes: https://webpack.js.org/configuration/devtool
4. You use `fetch('/api/movies')` in constructor and it is a not good decision. There is another lifecycle method that is a perfect match to fetch data - componentDidMount
Example: https://reactjs.org/docs/faq-ajax.html
Useful article: https://www.robinwieruch.de/react-fetching-data/

**Comment by trigolos** [comment]
5. Construction `set ENV_MODE = development` will not work on *nix machines. I suggest using cross-env package to resolve it - https://www.npmjs.com/package/cross-env

**Comment by akondratsky** [comment]
1. Done. Good construction with .filter, thank you.
2. I chose this form by next reasons. First, it's naturally readable and looks as question: "is production?" Second, you always have two states and can change it independently. Both of them can be "true" or "false"... So you can play with this options and it will be still readable for me. But as you insist I changed it to more shortly recording form.
3. Absolutely forgot about our talking. Of course, I have read about different devtools and investigated table of differences between them.
4. Yes, thank you. After class about components it became clear :)
5. Awesome! That's great idea, I'll embed it immediately.
