### ISSUE TITLE
Task 3

### ISSUE THREAD

**Issue by trigolos** [akondratsky/ReactJsMentoring2019Q1RU#2]
1. No need use "npx" in script section. You have already added cross-env to devDependencies.
It will work fine without "npx":
```json
"dev": "cross-env ENV_MODE=development webpack-dev-server"
```
By the way, for running multiple npm scripts in parallel or sequential you can use cross platform util  [npm-run-all](https://github.com/mysticatea/npm-run-all)

2. I recommend install [Webpack Bundle Analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer) to analyze size of webpack bundle. It seems that your bundle is not divided to vendor and your code.
I think it is worth removing the minChunks parameter from webpack config.

3. resolve.extension has ".js" and ".scss", it automatically resolve certain extensions. In the example below, you can omit the file extension. It's up to you of cause.
```javascript
import { App } from './components/App.js';
```

4. I advise you to place each component in JSX on a new line. This will improve readability.

Instead of:
```javascript
<div className='search-input__submit'><DummyButton text='Search' isActive={true} width='100px' /></div>
```
Write:
``` javascript
<div className='search-input__submit'>
    <DummyButton text='Search' isActive={true} width='100px' />
</div>
```

5. To operate with classNames I suggest you use [Classnames](https://github.com/JedWatson/classnames) library.
```javascript
className={ `button ${ isActive ? 'button-active' : 'button-inactive'}` }
```
To
```javascript
const classNames=cn('button', {
    'button-active': isActive,
    'button-inactive': !isActive
});
```

6. It is worth using [PropTypes](https://reactjs.org/docs/typechecking-with-proptypes.html). PropTypes allow you catch a lot of bugs with typechecking and it is best practice if you don't use TypeScript or another tool to typecheck.

7. Switcher component. 
```this.variants = props.variants;``` inside constructor. If variants change you will not see new variants because you save it inside constructor. 
This also applies to ```this.onChange = this.props.onChange```.
Better as it seems to me:
```javascript
const { variants = [] } = this.props;

return (
    <div className='switcher'>
        {variants.map((variantName) => (
            <div className='switcher__button' key={variantName}>
                <DummyButton
                    text={variantName}
                    width='100%'
                    onClick={this.btnClickHandler}
                    isActive={variantName === this.state.currentActive}/>
            </div>
        ))}
    </div>
);
```

**Comment by akondratsky** [comment]
It's my idea of hell, to use PropTypes. But I tried. Really when on other hand we have TS, I don't see reason to use PropTypes... It looks like the right thing was made when React's authors exclude it and put into outer package.

Thank you very much for npm-run-all, webpack bundle analyzer plugin and example of refactored code. I see, I need more experience in reading contemporary code.

'classnames' is great also, I included it in my study project and used in those case.
