### ISSUE TITLE
Task 7. SSR

### ISSUE THREAD

**Issue by trigolos** [akondratsky/ReactJsMentoring2019Q1RU#4]
1. Failed to launch production version (npm run prod).
I got ReferenceError:: MiniCssExtractPlugin is not defined. 
I fix it and path to css file. Only after that production version earned.

2. Page with film (e.g - /film/447365) requests data from the server. Despite the fact that the SSR worked
![2019-05-15_23h13_07](https://user-images.githubusercontent.com/7376989/57802514-31a8e580-7767-11e9-9f90-3f244946bacf.png)

3. Dispatch will return promise if filmsFetchData returns promise
```javascript
await store.dispatch(await filmsFetchData())
```
To:
```javascript
await store.dispatch(filmsFetchData())
```

**Comment by akondratsky** [comment]
Thanks for your attention. Issues was solved.
